-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- Activa el modo "cowboy" cuando todo cargue
-- Activa el modo "cowboy" cuando Lazy termine de cargar (evento User VeryLazy)
-- Activa el modo "cowboy" cuando Lazy termine de cargar
